USE test;
DROP TABLE IF EXISTS USERCOURSES;
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    USERNAME VARCHAR(255) NOT NULL,
    USERPASSWORD TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PRIMARY KEY (USERNAME)
);
CREATE TABLE USERCOURSES(
    id INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    COURSENUMBER INTEGER NOT NULL,
    COURSETITLE INTEGER NOT NULL,
    INSTRUCTOR TEXT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);